language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

addons:
  apt:
    packages:
      - devscripts
      - fakeroot
      - debhelper

before_install:
  - wget --no-verbose -O- https://github.com/VirusTotal/yara/archive/v3.8.1.tar.gz | tar -C ${TRAVIS_BUILD_DIR} -xzf -
  - ( cd ${TRAVIS_BUILD_DIR}/yara-3.8.1 && ./bootstrap.sh && ./configure && make )
  - export CGO_CFLAGS=-I${TRAVIS_BUILD_DIR}/yara-3.8.1/libyara/include
  - export CGO_LDFLAGS=-L${TRAVIS_BUILD_DIR}/yara-3.8.1/libyara/.libs
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/yara-3.8.1/libyara/.libs
  - export PKG_CONFIG_PATH=${TRAVIS_BUILD_DIR}/yara-3.8.1/libyara/

install:
  - make

script:
  - make tests
  - make deb
